### ISSUE TITLE
Last electricity carbon intensity extract

### ISSUE THREAD

**Issue by AirLoren** [climatiq/Open-Emission-Factors-DB#231]
Hi,

First of all, thanks for your great job.
At Boavizta.org, we maintain an up to date database with most relevant (last know + including transport and delivery when available) electricity carbon intensity from several countries.
This database is mainly built with data centralized on Climatiq and I think many other projects such as [Codecarbon](https://github.com/mlco2/codecarbon) should have same needs.
We suggest to create and maintain this database on your repo to allow other projects to use it.
Of course, we will be delighted to contribute to this database.

**Comment by grindcode** [comment]
Hey @AirLoren, thank you for the kind words.

Your suggestion to contribute sounds great! It will bring great value to the project, and allows us to share the effort of maintaining this data. At the same we are very interested in building the right tools and approach to facilitate future contributions from more teams like yourself. 

Currently we try to direct all contributions to the same main CSV file, since this allows for easier comparison and metadata expansion over time. Let us know what you think about this approach, and we can discuss if any potential barriers need to be adjusted.

We will be very happy to support you in the process!

**Comment by AirLoren** [comment]
Hi @grindcode,

I totally agree you should keep the main CSV file as a reference.
What do you think about building a script that will parse the main CSV file to extract last available and most relevant data for each country? Then, you could run it to publish an up to date dataset for electricity carbon intensity on your git.
I can work on the script but I will need your help to know how I can identify most relevant data (in priority those which correspond to the electricity consumed by the end user and if not available, the closest value to it)

**Comment by grindcode** [comment]
With the idea of keeping this repository as focused as possible, we do maintain our parsers separately, since they are geared towards using this data in the query engine part of the Climatiq API.

For generic data processing, we also published the [OEFDB Python SDK](https://github.com/climatiq/python-oefdb-sdk) package, which is designed for contribution and data analysis, and actively used and maintained by @AnastasiaLobanova.

Please have a look before doing any work. Maybe there are some overlaps that could be handled there.
