### ISSUE TITLE
Issue splitting up activity_id

### ISSUE THREAD

**Issue by alexandrulesi** [climatiq/Open-Emission-Factors-DB#311]
Hi folks,

we're trying to map the OEFDB emission factors to the structure we use in our db. We keep parameters like fuel type or energy source as separate values.

We're having issues decoding the activity_id. The `-` symbol is meant to split up sub-ids, but that does not turn out to be the case, like for e.g. with `heat-and-steam-type_[....]`.

Then there doesn't seem to be any split between key and value pairs. So for `fuel_type_avgas` the split is at the second underscore, but for `class_premium_economy` it's at the first. Then sometimes there seems to be just a value, like with `paper_and_cardboard`.

Is there any way to do this? Or any other way to get the sub id key values?

**Comment by patstirling** [comment]
Hi @alexandrulesi - have a look at https://github.com/climatiq/Open-Emission-Factors-DB/blob/main/Sector-Category-ID_structure.csv to start with. That said there are definitely some errors in the data, as you've pointed out - so please do let us know specifics if you spot them (rather than do a PR to fix them - at the moment we are avoiding making any changes to live IDs as it will cause instability for implementations that are on them, but we are keeping a list of any we spot and will do a batch update with a version release (most likely).

**Comment by alexandrulesi** [comment]
Well concretely that `-` is used for purposes other than splitting up sub-ids. Those can generally all be `_` instead. `heat_and_steam_type_[....]`

Then I get the impression there should be another delimiter between key and values of sub-ids. So something like `fuel_type:avgas-fuel_use:aviation`

This would make decoding the id really simple.

**Comment by patstirling** [comment]
Well put - this is something that we've been looking into for a while, as it's become clear that the current structure isn't fit for purpose as it stands. We'll update soon on how we go forward with this - it's a topic of discussion right now! I'll close the issue for now as we are unable to make any changes to structure currently.
